default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: cityenglishproject_development
  host: localhost

test:
  <<: *default
  database: cityenglishproject_test

production:
  <<: *default
  database: cityenglishproject_production
  username: cityenglishproject
  password: <%= ENV['CEP_ONLINE_DATABASE_PASSWORD'] %>